<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Strings for component 'enrol_ilios', language 'en'.
 *
 * @package    enrol_ilios
 * @copyright  2015 Carson Tam  {@email carson.tam@ucsf.edu}
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

$string['addgroup'] = 'Add to group';
$string['ajaxmore'] = 'More...';
$string['apikey'] = 'Ilios API key';
$string['apikey_desc'] = 'Enter the API key obtained from your Ilios server.';
$string['assignrole'] = 'Assign role';
$string['enrol'] = 'Enrol Ilios users';
$string['enrolusers'] = 'Enrol users';
$string['group'] = 'Learner group';
$string['host_url'] = 'Host URL';
$string['host_url_desc'] = 'Type Ilios server IP address or host URL.';
$string['ilios'] = 'Ilios';
$string['iliossearch'] = 'Search';
$string['ilios:config'] = 'Configure ilios instances';
$string['ilios:unenrol'] = 'Unenrol suspended users';
$string['instanceexists'] = 'Ilios enrolment is already synchronised with selected role';
$string['pluginname'] = 'Ilios enrolment sync';
$string['pluginname_desc'] = 'Ilios enrolment plugin synchronises members with course participants.';
$string['program'] = 'Program';
$string['programyear'] = 'Program year';
$string['school'] = 'School';
$string['secret'] = 'Ilios secret';
$string['secret_desc'] = 'Enter the secret string generated by your Ilios server here.';
$string['status'] = 'Active';
